// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlw3wo7708Pb1obX0zfijAcRQx36UK5xQ',
    appId: '1:79622136056:web:977a05bf5a7d8edf725b0d',
    messagingSenderId: '79622136056',
    projectId: 'food-67734',
    authDomain: 'food-67734.firebaseapp.com',
    storageBucket: 'food-67734.appspot.com',
    measurementId: 'G-GB2XCV86RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbieXpxPzYghCV62Kmnh6S_a5GezZ9FN0',
    appId: '1:79622136056:android:75a37ae0ab7ede1a725b0d',
    messagingSenderId: '79622136056',
    projectId: 'food-67734',
    storageBucket: 'food-67734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnQX3HMiNME6i-1O69W760wSTBHJR5tcM',
    appId: '1:79622136056:ios:ec7d7d2480ffde65725b0d',
    messagingSenderId: '79622136056',
    projectId: 'food-67734',
    storageBucket: 'food-67734.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnQX3HMiNME6i-1O69W760wSTBHJR5tcM',
    appId: '1:79622136056:ios:ec7d7d2480ffde65725b0d',
    messagingSenderId: '79622136056',
    projectId: 'food-67734',
    storageBucket: 'food-67734.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlw3wo7708Pb1obX0zfijAcRQx36UK5xQ',
    appId: '1:79622136056:web:81a82adde8bd6e00725b0d',
    messagingSenderId: '79622136056',
    projectId: 'food-67734',
    authDomain: 'food-67734.firebaseapp.com',
    storageBucket: 'food-67734.appspot.com',
    measurementId: 'G-LE9ZZ42DH7',
  );
}
